PicFR041childsbedroompng_Bank equ 0
PicFR041childsbedroompng_Ref equ 0
PicFR041childsbedroompng_ParentRef equ 255

PicFR083childsbedroomV2png_Bank equ 0
PicFR083childsbedroomV2png_Ref equ 3
PicFR083childsbedroomV2png_ParentRef equ PicFR041childsbedroompng_Ref 

PicFR084childsbedroomV3png_Bank equ 0
PicFR084childsbedroomV3png_Ref equ 6
PicFR084childsbedroomV3png_ParentRef equ PicFR041childsbedroompng_Ref 

PicFR085childsbedroomV4png_Bank equ 0
PicFR085childsbedroomV4png_Ref equ 9
PicFR085childsbedroomV4png_ParentRef equ PicFR041childsbedroompng_Ref 

DiskMap_Intro_Screens_Bank0 equ &3BC1
PicEp2Intropng_Bank equ 1
PicEp2Intropng_Ref equ 0
PicEp2Intropng_ParentRef equ 255

PicEp2IntroRedrawpng_Bank equ 1
PicEp2IntroRedrawpng_Ref equ 3
PicEp2IntroRedrawpng_ParentRef equ 255

DiskMap_Intro_Screens_Bank1 equ &3BC2
PicFR010BochanlickinglollipopV1png_Bank equ 2
PicFR010BochanlickinglollipopV1png_Ref equ 0
PicFR010BochanlickinglollipopV1png_ParentRef equ 255

PicFR011BochanlickinglollipopV2png_Bank equ 2
PicFR011BochanlickinglollipopV2png_Ref equ 3
PicFR011BochanlickinglollipopV2png_ParentRef equ PicFR010BochanlickinglollipopV1png_Ref 

DiskMap_Intro_Screens_Bank2 equ &3BC3
PicFR020ChibikobydoorCutthroatguypng_Bank equ 3
PicFR020ChibikobydoorCutthroatguypng_Ref equ 0
PicFR020ChibikobydoorCutthroatguypng_ParentRef equ 255

PicFR012bochanTVpng_Bank equ 3
PicFR012bochanTVpng_Ref equ 3
PicFR012bochanTVpng_ParentRef equ 255

PicFR026Chibikobydoorpng_Bank equ 3
PicFR026Chibikobydoorpng_Ref equ 6
PicFR026Chibikobydoorpng_ParentRef equ 255

PicFR078ChibikobydoorAngrypng_Bank equ 3
PicFR078ChibikobydoorAngrypng_Ref equ 9
PicFR078ChibikobydoorAngrypng_ParentRef equ 255

PicFR027Chibikoflyingawayfromhousepng_Bank equ 3
PicFR027Chibikoflyingawayfromhousepng_Ref equ 12
PicFR027Chibikoflyingawayfromhousepng_ParentRef equ 255

PicFR028Chibikoflyingacrossrockydesertpng_Bank equ 3
PicFR028Chibikoflyingacrossrockydesertpng_Ref equ 15
PicFR028Chibikoflyingacrossrockydesertpng_ParentRef equ 255

PicFR033Chibikopaintingtownsignpng_Bank equ 3
PicFR033Chibikopaintingtownsignpng_Ref equ 18
PicFR033Chibikopaintingtownsignpng_ParentRef equ 255

DiskMap_Intro_Screens_Bank3 equ &3BC4
PicFR077SignV2png_Bank equ 4
PicFR077SignV2png_Ref equ 0
PicFR077SignV2png_ParentRef equ 255

PicFR029chibikoFlyingacrossdesertreversepng_Bank equ 4
PicFR029chibikoFlyingacrossdesertreversepng_Ref equ 3
PicFR029chibikoFlyingacrossdesertreversepng_ParentRef equ 255

PicFR039chibikoWalkingacrosstrainlinepng_Bank equ 4
PicFR039chibikoWalkingacrosstrainlinepng_Ref equ 6
PicFR039chibikoWalkingacrosstrainlinepng_ParentRef equ 255

PicFR030chibikoHoldingcollarbigairlinetagNameBochanPropertyofChibikopng_Bank equ 4
PicFR030chibikoHoldingcollarbigairlinetagNameBochanPropertyofChibikopng_Ref equ 9
PicFR030chibikoHoldingcollarbigairlinetagNameBochanPropertyofChibikopng_ParentRef equ 255

PicFR031ChibikoLookingaroundseesgiantbrokenlollipoppng_Bank equ 4
PicFR031ChibikoLookingaroundseesgiantbrokenlollipoppng_Ref equ 12
PicFR031ChibikoLookingaroundseesgiantbrokenlollipoppng_ParentRef equ 255

PicFR012bochanTVbpng_Bank equ 4
PicFR012bochanTVbpng_Ref equ 15
PicFR012bochanTVbpng_ParentRef equ 255

PicFR014Bochanhandholdingfliermassivelollipopsalepng_Bank equ 4
PicFR014Bochanhandholdingfliermassivelollipopsalepng_Ref equ 18
PicFR014Bochanhandholdingfliermassivelollipopsalepng_ParentRef equ 255

PicFR013bochanTVmischivouslookonfacepng_Bank equ 4
PicFR013bochanTVmischivouslookonfacepng_Ref equ 21
PicFR013bochanTVmischivouslookonfacepng_ParentRef equ PicFR012bochanTVbpng_Ref 

DiskMap_Intro_Screens_Bank4 equ &3BC5
PicFR073CandyStoreChompaChumpsBochanInsidepng_Bank equ 5
PicFR073CandyStoreChompaChumpsBochanInsidepng_Ref equ 0
PicFR073CandyStoreChompaChumpsBochanInsidepng_ParentRef equ 255

PicFR018CandyStoreChompaChumpsSignGiantlolipopsalesakuyainbackgrounpng_Bank equ 5
PicFR018CandyStoreChompaChumpsSignGiantlolipopsalesakuyainbackgrounpng_Ref equ 3
PicFR018CandyStoreChompaChumpsSignGiantlolipopsalesakuyainbackgrounpng_ParentRef equ PicFR073CandyStoreChompaChumpsBochanInsidepng_Ref 

PicFR019CandyStoreBochanwalksoutwithgiantlollipoppng_Bank equ 5
PicFR019CandyStoreBochanwalksoutwithgiantlollipoppng_Ref equ 6
PicFR019CandyStoreBochanwalksoutwithgiantlollipoppng_ParentRef equ PicFR073CandyStoreChompaChumpsBochanInsidepng_Ref 

PicFR074Bocchanwalksacrosstraintrackpng_Bank equ 5
PicFR074Bocchanwalksacrosstraintrackpng_Ref equ 9
PicFR074Bocchanwalksacrosstraintrackpng_ParentRef equ 255

PicFR017Bocchanwalksacrosstraintrackdropslolipopontrackpng_Bank equ 5
PicFR017Bocchanwalksacrosstraintrackdropslolipopontrackpng_Ref equ 12
PicFR017Bocchanwalksacrosstraintrackdropslolipopontrackpng_ParentRef equ PicFR074Bocchanwalksacrosstraintrackpng_Ref 

PicFR081startslickingitwhileitsstucktotrackpng_Bank equ 5
PicFR081startslickingitwhileitsstucktotrackpng_Ref equ 15
PicFR081startslickingitwhileitsstucktotrackpng_ParentRef equ 255

PicFR053traincomingnomovementpng_Bank equ 5
PicFR053traincomingnomovementpng_Ref equ 18
PicFR053traincomingnomovementpng_ParentRef equ 255

PicFR054trainclosernomovementpng_Bank equ 5
PicFR054trainclosernomovementpng_Ref equ 21
PicFR054trainclosernomovementpng_ParentRef equ 255

PicFR055trainUrgentnomovementpng_Bank equ 5
PicFR055trainUrgentnomovementpng_Ref equ 24
PicFR055trainUrgentnomovementpng_ParentRef equ 255

DiskMap_Intro_Screens_Bank5 equ &3BC6
PicFR056TrainSquelchpng_Bank equ 6
PicFR056TrainSquelchpng_Ref equ 0
PicFR056TrainSquelchpng_ParentRef equ 255

PicFR031ChibikoLookingaroundseesgiantbrokenlollipopbpng_Bank equ 6
PicFR031ChibikoLookingaroundseesgiantbrokenlollipopbpng_Ref equ 3
PicFR031ChibikoLookingaroundseesgiantbrokenlollipopbpng_ParentRef equ 255

PicFR040Chibikowithcartrandomlimbsstickingoutpng_Bank equ 6
PicFR040Chibikowithcartrandomlimbsstickingoutpng_Ref equ 6
PicFR040Chibikowithcartrandomlimbsstickingoutpng_ParentRef equ 255

PicFR034ChibikosewingfootCutfingersFootonbackwardspng_Bank equ 6
PicFR034ChibikosewingfootCutfingersFootonbackwardspng_Ref equ 9
PicFR034ChibikosewingfootCutfingersFootonbackwardspng_ParentRef equ 255

PicFR024ChibikoBlackmasspng_Bank equ 6
PicFR024ChibikoBlackmasspng_Ref equ 12
PicFR024ChibikoBlackmasspng_ParentRef equ 255

PicFR016Bochanresurrectedpng_Bank equ 6
PicFR016Bochanresurrectedpng_Ref equ 15
PicFR016Bochanresurrectedpng_ParentRef equ 255

DiskMap_Intro_Screens_Bank6 equ &3BC7
PicFR076newcharactersinshadowpng_Bank equ 7
PicFR076newcharactersinshadowpng_Ref equ 0
PicFR076newcharactersinshadowpng_ParentRef equ 255

PicFR003blooddonationtentwithbloodstainedhandprintspng_Bank equ 7
PicFR003blooddonationtentwithbloodstainedhandprintspng_Ref equ 3
PicFR003blooddonationtentwithbloodstainedhandprintspng_ParentRef equ 255

PicFR032Chibikonurseangrybochanbysidepng_Bank equ 7
PicFR032Chibikonurseangrybochanbysidepng_Ref equ 6
PicFR032Chibikonurseangrybochanbysidepng_ParentRef equ 255

PicFR057Yumechallengefromintroyumibysidepng_Bank equ 7
PicFR057Yumechallengefromintroyumibysidepng_Ref equ 9
PicFR057Yumechallengefromintroyumibysidepng_ParentRef equ 255

PicFR063Yumichallengefromintroyumebysidepng_Bank equ 7
PicFR063Yumichallengefromintroyumebysidepng_Ref equ 12
PicFR063Yumichallengefromintroyumebysidepng_ParentRef equ 255

DiskMap_Intro_Screens_Bank7 equ &3BC8
