PicFR023ChibikoandbochanendsequenceChibikosmugbochangunkpng_Bank equ 0
PicFR023ChibikoandbochanendsequenceChibikosmugbochangunkpng_Ref equ 0
PicFR023ChibikoandbochanendsequenceChibikosmugbochangunkpng_ParentRef equ 255

PicFR022ChibikoandbochanendsequenceChibikosurprisepng_Bank equ 0
PicFR022ChibikoandbochanendsequenceChibikosurprisepng_Ref equ 3
PicFR022ChibikoandbochanendsequenceChibikosurprisepng_ParentRef equ 255

PicFR021ChibikoandbochanendsequenceBochanshrugpng_Bank equ 0
PicFR021ChibikoandbochanendsequenceBochanshrugpng_Ref equ 6
PicFR021ChibikoandbochanendsequenceBochanshrugpng_ParentRef equ 255

PicFR067yumiandyumeendsequencegunkpng_Bank equ 0
PicFR067yumiandyumeendsequencegunkpng_Ref equ 9
PicFR067yumiandyumeendsequencegunkpng_ParentRef equ 255

PicFR068yumiandyumeendsequenceleavepng_Bank equ 0
PicFR068yumiandyumeendsequenceleavepng_Ref equ 12
PicFR068yumiandyumeendsequenceleavepng_ParentRef equ 255

PicFR069yumiandyumeendsequenceleavequestionpng_Bank equ 0
PicFR069yumiandyumeendsequenceleavequestionpng_Ref equ 15
PicFR069yumiandyumeendsequenceleavequestionpng_ParentRef equ 255

DiskMap_Outro_Screens_Bank0 equ &34C1
PicFR022ChibikoandbochanendsequenceChibikosurprisebpng_Bank equ 1
PicFR022ChibikoandbochanendsequenceChibikosurprisebpng_Ref equ 0
PicFR022ChibikoandbochanendsequenceChibikosurprisebpng_ParentRef equ 255

PicFR085ChibikoendsequenceChibikoglumpng_Bank equ 1
PicFR085ChibikoendsequenceChibikoglumpng_Ref equ 3
PicFR085ChibikoendsequenceChibikoglumpng_ParentRef equ 255

PicFR023ChibikoandbochanendsequenceChibikosmugbochangunkbpng_Bank equ 1
PicFR023ChibikoandbochanendsequenceChibikosmugbochangunkbpng_Ref equ 6
PicFR023ChibikoandbochanendsequenceChibikosmugbochangunkbpng_ParentRef equ 255

PicFR067yumiandyumeendsequencegunkbpng_Bank equ 1
PicFR067yumiandyumeendsequencegunkbpng_Ref equ 9
PicFR067yumiandyumeendsequencegunkbpng_ParentRef equ 255

PicFR068yumiandyumeendsequenceleavebpng_Bank equ 1
PicFR068yumiandyumeendsequenceleavebpng_Ref equ 12
PicFR068yumiandyumeendsequenceleavebpng_ParentRef equ 255

PicFR069yumiandyumeendsequenceleavequestionbpng_Bank equ 1
PicFR069yumiandyumeendsequenceleavequestionbpng_Ref equ 15
PicFR069yumiandyumeendsequenceleavequestionbpng_ParentRef equ 255

DiskMap_Outro_Screens_Bank1 equ &34C2
PicFR004bochanendsequencebochansmugpng_Bank equ 2
PicFR004bochanendsequencebochansmugpng_Ref equ 0
PicFR004bochanendsequencebochansmugpng_ParentRef equ 255

PicFR005bochanendsequencebochancautiouspng_Bank equ 2
PicFR005bochanendsequencebochancautiouspng_Ref equ 3
PicFR005bochanendsequencebochancautiouspng_ParentRef equ 255

PicFR067yumiandyumeendsequencegunkcpng_Bank equ 2
PicFR067yumiandyumeendsequencegunkcpng_Ref equ 6
PicFR067yumiandyumeendsequencegunkcpng_ParentRef equ 255

PicFR068yumiandyumeendsequenceleavecpng_Bank equ 2
PicFR068yumiandyumeendsequenceleavecpng_Ref equ 9
PicFR068yumiandyumeendsequenceleavecpng_ParentRef equ 255

PicFR069yumiandyumeendsequenceleavequestioncpng_Bank equ 2
PicFR069yumiandyumeendsequenceleavequestioncpng_Ref equ 12
PicFR069yumiandyumeendsequenceleavequestioncpng_ParentRef equ 255

PicFR072yumiandyumeendsequenceGratitudepng_Bank equ 2
PicFR072yumiandyumeendsequenceGratitudepng_Ref equ 15
PicFR072yumiandyumeendsequenceGratitudepng_ParentRef equ 255

DiskMap_Outro_Screens_Bank2 equ &34C3
PicFR079SakuyaExplode1png_Bank equ 3
PicFR079SakuyaExplode1png_Ref equ 0
PicFR079SakuyaExplode1png_ParentRef equ 255

PicFR080SakuyaExplode2png_Bank equ 3
PicFR080SakuyaExplode2png_Ref equ 3
PicFR080SakuyaExplode2png_ParentRef equ 255

DiskMap_Outro_Screens_Bank3 equ &34C4
PicThanksForPlaying1png_Bank equ 4
PicThanksForPlaying1png_Ref equ 0
PicThanksForPlaying1png_ParentRef equ 255

PicThanksForPlaying1bpng_Bank equ 4
PicThanksForPlaying1bpng_Ref equ 3
PicThanksForPlaying1bpng_ParentRef equ PicThanksForPlaying2png_Ref 

PicThanksForPlaying2png_Bank equ 4
PicThanksForPlaying2png_Ref equ 6
PicThanksForPlaying2png_ParentRef equ PicThanksForPlaying1png_Ref 

DiskMap_Outro_Screens_Bank4 equ &34C5
PicEndmessagepng_Bank equ 5
PicEndmessagepng_Ref equ 0
PicEndmessagepng_ParentRef equ 255

DiskMap_Outro_Screens_Bank5 equ &34C6
