;read "Ep2Intro1.asm"
;read "Ep2Intro2.asm"
;read "Ep2Intro3.asm"
;read "Ep2Intro4.asm"
;read "Ep2Intro5.asm"
;read "Ep2Intro6.asm"
;read "Ep2Intro7.asm"
read "Ep2Intro8.asm"


;read "Ep2EndSeqIntro0.asm"
;read "Ep2EndSeqIntro1.asm"
;read "Ep2EndSeqIntro2.asm"
;read "Ep2EndSeqIntro3.asm"
;read "Ep2EndSeqIntro4.asm"
;read "Ep2EndSeqIntro5.asm"

;read "Ep2Outro0.asm"
;read "Ep2Outro1.asm"
;read "Ep2Outro2.asm"
;read "Ep2Outro3.asm"
; - modified ; read "Ep2Outro4.asm"
;read "Ep2Outro5.asm"